version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: infra/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    
  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    # No `ports:` key — Compose will assign a random host port automatically. 