version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: infra/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379" 